version: '3.8'

services:
  mysqldb:
    image: mysql
    container_name: mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
      - ./backend/online_compiler.sql:/docker-entrypoint-initdb.d/dump.sql:ro
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  backend:
    depends_on:
      - mysqldb
    container_name: nodejs
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
    stdin_open: true
    tty: true
  frontend:
    depends_on:
      - backend
    container_name: vuejs
    build: ./frontend
    restart: unless-stopped
    ports:
      - $VUE_LOCAL_PORT:$VUE_DOCKER_PORT
volumes:
  db: